blank_issues_enabled: true
contact_links:
  - name: n8n Community Forum
    url: https://community.n8n.io
    about: For general n8n questions, use the official community forum
  - name: n8n Documentation
    url: https://docs.n8n.io
    about: Check the official n8n documentation
